version: '2.2'

services:
  spring-boot-application:
    container_name: registration
    build:
      context: /
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/user_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
  application_db:
    container_name: registration_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=user_db
          - MYSQL_USER=user
          - MYSQL_PASSWORD=password
